[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
first_contract = "D3LMDue6hQpkjM5SUFcFnc5i2GH9Qk2FjNwngGG5Zhfe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
